name: ibm_money_app
description: "돈을 시간으로 바꿔 보여주는 저축 목표 및 소비 관리 앱"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  excel_plus: ^2.14.3
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.5.5
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/shop/
