// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQvWKuqx1hva6Tr5uFpekRv-4-V2WjLvo',
    appId: '1:78964999448:web:1af7230fbbd2e351374a6d',
    messagingSenderId: '78964999448',
    projectId: 'ibankmanager-c7cb8',
    authDomain: 'ibankmanager-c7cb8.firebaseapp.com',
    storageBucket: 'ibankmanager-c7cb8.firebasestorage.app',
    measurementId: 'G-TFY93VK3XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPnEhujRxkm15aHNTSVHZQsHsq-E9kg6E',
    appId: '1:78964999448:android:3ffce3b3a8b764f5374a6d',
    messagingSenderId: '78964999448',
    projectId: 'ibankmanager-c7cb8',
    storageBucket: 'ibankmanager-c7cb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvv4i3DsAIiUjCZ1Uh6zgmpBTJ4avZTBo',
    appId: '1:78964999448:ios:4d091eab63ddeed7374a6d',
    messagingSenderId: '78964999448',
    projectId: 'ibankmanager-c7cb8',
    storageBucket: 'ibankmanager-c7cb8.firebasestorage.app',
    iosBundleId: 'com.ibm.money.ibmMoneyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQvWKuqx1hva6Tr5uFpekRv-4-V2WjLvo',
    appId: '1:78964999448:web:c4f8851e9672e5f3374a6d',
    messagingSenderId: '78964999448',
    projectId: 'ibankmanager-c7cb8',
    authDomain: 'ibankmanager-c7cb8.firebaseapp.com',
    storageBucket: 'ibankmanager-c7cb8.firebasestorage.app',
    measurementId: 'G-HRDYR2KC31',
  );
}
