import 'package:flutter/material.dart';

import 'models.dart';

const userName = '김은찬';
const accountLabel = '내 계좌';
const remainingBalance = 257230;

const initialGoal = SavingsGoal(
  name: 'AirPods',
  imageAsset: 'assets/images/goal-item.png',
  price: 200000,
  saved: 80000,
  savingAmount: 5000,
  savingPeriod: SavingPeriod.daily,
);

final transactions = <MoneyTransaction>[
  MoneyTransaction(
    id: 't1',
    merchant: '배달의민족',
    category: '배달',
    amount: 19800,
    date: DateTime(2026, 8, 19),
  ),
  MoneyTransaction(
    id: 't2',
    merchant: '스타벅스',
    category: '카페',
    amount: 6100,
    date: DateTime(2026, 8, 18),
  ),
  MoneyTransaction(
    id: 't3',
    merchant: 'CU 편의점',
    category: '식비',
    amount: 4500,
    date: DateTime(2026, 8, 17),
  ),
  MoneyTransaction(
    id: 't4',
    merchant: '넷플릭스',
    category: '구독',
    amount: 17000,
    date: DateTime(2026, 8, 16),
  ),
  MoneyTransaction(
    id: 't5',
    merchant: '버스',
    category: '교통',
    amount: 1400,
    date: DateTime(2026, 8, 16),
  ),
  MoneyTransaction(
    id: 't6',
    merchant: '배달의민족',
    category: '배달',
    amount: 22000,
    date: DateTime(2026, 8, 14),
  ),
  MoneyTransaction(
    id: 't7',
    merchant: '메가커피',
    category: '카페',
    amount: 3500,
    date: DateTime(2026, 8, 13),
  ),
  MoneyTransaction(
    id: 't8',
    merchant: '교보문고',
    category: '쇼핑',
    amount: 15800,
    date: DateTime(2026, 8, 12),
  ),
  MoneyTransaction(
    id: 't9',
    merchant: '스타벅스',
    category: '카페',
    amount: 5500,
    date: DateTime(2026, 8, 10),
  ),
  MoneyTransaction(
    id: 't10',
    merchant: '지하철',
    category: '교통',
    amount: 1400,
    date: DateTime(2026, 8, 9),
  ),
  MoneyTransaction(
    id: 't11',
    merchant: '배달의민족',
    category: '배달',
    amount: 18500,
    date: DateTime(2026, 8, 7),
  ),
  MoneyTransaction(
    id: 't12',
    merchant: 'GS25',
    category: '식비',
    amount: 3200,
    date: DateTime(2026, 8, 5),
  ),
  MoneyTransaction(
    id: 't13',
    merchant: '배달의민족',
    category: '배달',
    amount: 16200,
    date: DateTime(2026, 7, 28),
  ),
  MoneyTransaction(
    id: 't14',
    merchant: '스타벅스',
    category: '카페',
    amount: 4500,
    date: DateTime(2026, 7, 22),
  ),
  MoneyTransaction(
    id: 't15',
    merchant: '버스',
    category: '교통',
    amount: 2800,
    date: DateTime(2026, 7, 18),
  ),
  MoneyTransaction(
    id: 't16',
    merchant: '쿠팡',
    category: '쇼핑',
    amount: 12900,
    date: DateTime(2026, 7, 12),
  ),
  MoneyTransaction(
    id: 't17',
    merchant: '넷플릭스',
    category: '구독',
    amount: 17000,
    date: DateTime(2026, 7, 16),
  ),
  MoneyTransaction(
    id: 't18',
    merchant: '메가커피',
    category: '카페',
    amount: 2000,
    date: DateTime(2026, 7, 8),
  ),
];

const categoryMeta = <String, CategoryInfo>{
  '배달': CategoryInfo(color: Color(0xFFFF8A3D), emoji: '🛵'),
  '카페': CategoryInfo(color: Color(0xFFC49A6C), emoji: '☕'),
  '식비': CategoryInfo(color: Color(0xFF6DB36B), emoji: '🍚'),
  '교통': CategoryInfo(color: Color(0xFF5B9CF5), emoji: '🚌'),
  '구독': CategoryInfo(color: Color(0xFFB57BE8), emoji: '📺'),
  '쇼핑': CategoryInfo(color: Color(0xFFF071A5), emoji: '🛍️'),
  '생활': CategoryInfo(color: Color(0xFF78A89A), emoji: '🏠'),
  '의료': CategoryInfo(color: Color(0xFFE97777), emoji: '🩺'),
  '여가': CategoryInfo(color: Color(0xFF8D7BE8), emoji: '🎮'),
  '이체': CategoryInfo(color: Color(0xFF7E95B5), emoji: '↔️'),
  '현금': CategoryInfo(color: Color(0xFF9B8A70), emoji: '💵'),
  '기타': CategoryInfo(color: Color(0xFF87958A), emoji: '🧾'),
};

const shopProducts = <ShopProduct>[
  ShopProduct(
    id: 'p1',
    rank: 1,
    rankChange: 4,
    brand: '스파오',
    name: '하찌 니트 스웨터',
    shortName: '하찌 니트',
    originalPrice: 39900,
    price: 29900,
    imageAsset: 'assets/images/shop/knit.png',
    colors: [Color(0xFFCFC7BF), Color(0xFF8A8A8A)],
    tabs: {'ranking', 'sale'},
  ),
  ShopProduct(
    id: 'p2',
    rank: 2,
    rankChange: -2,
    brand: '유니클로',
    name: '플리스 집업 자켓',
    shortName: '플리스 집업',
    originalPrice: 59900,
    price: 49900,
    imageAsset: 'assets/images/shop/fleece.png',
    colors: [Color(0xFFF3EFE6)],
    tabs: {'ranking', 'new'},
  ),
  ShopProduct(
    id: 'p3',
    rank: 3,
    rankChange: 1,
    brand: '커버낫',
    name: '와이드 카고 팬츠',
    shortName: '카고 팬츠',
    originalPrice: 69000,
    price: 49000,
    imageAsset: 'assets/images/shop/cargo.png',
    colors: [Color(0xFFD8C7A8), Color(0xFF2F2F2F)],
    tabs: {'ranking', 'sale'},
  ),
  ShopProduct(
    id: 'p4',
    rank: 4,
    rankChange: 6,
    brand: '잔스포츠',
    name: '미니 크로스 백',
    shortName: '크로스백',
    originalPrice: 45000,
    price: 35000,
    imageAsset: 'assets/images/shop/bag.png',
    colors: [Color(0xFF111111)],
    tabs: {'ranking', 'new'},
  ),
  ShopProduct(
    id: 'p5',
    rank: 5,
    rankChange: -1,
    brand: '젠틀데이',
    name: '스퀘어 선글라스',
    shortName: '선글라스',
    originalPrice: 89000,
    price: 69000,
    imageAsset: 'assets/images/shop/sunglasses.png',
    colors: [Color(0xFF111111)],
    tabs: {'ranking', 'special'},
  ),
  ShopProduct(
    id: 'p6',
    rank: 6,
    rankChange: 3,
    brand: '리바이스',
    name: '라이트 데님 자켓',
    shortName: '데님 자켓',
    originalPrice: 98000,
    price: 79000,
    imageAsset: 'assets/images/shop/denim.png',
    colors: [Color(0xFF7EA0C4)],
    tabs: {'ranking', 'special'},
  ),
  ShopProduct(
    id: 'p7',
    rank: 7,
    rankChange: 1,
    brand: '에잇세컨즈',
    name: '에센셜 기모 후드',
    shortName: '기모 후드',
    originalPrice: 54000,
    price: 39900,
    imageAsset: 'assets/images/shop/hoodie.png',
    colors: [Color(0xFF111111), Color(0xFF6B6B6B)],
    tabs: {'ranking', 'sale'},
  ),
  ShopProduct(
    id: 'p8',
    rank: 8,
    rankChange: 13,
    brand: '디스커버리',
    name: '버킷 디워커 V2',
    shortName: '디워커 스니커즈',
    originalPrice: 89000,
    price: 69000,
    imageAsset: 'assets/images/shop/sneakers.png',
    colors: [Color(0xFFF4F4F4), Color(0xFFC8C8C8)],
    tabs: {'ranking', 'new'},
  ),
  ShopProduct(
    id: 'p9',
    rank: 9,
    rankChange: 2,
    brand: '커버낫',
    name: 'C로고 볼캡',
    shortName: '볼캡',
    originalPrice: 29000,
    price: 19900,
    imageAsset: 'assets/images/shop/cap.png',
    colors: [Color(0xFF111111)],
    tabs: {'ranking', 'sale'},
  ),
  ShopProduct(
    id: 'p10',
    rank: 10,
    rankChange: 3,
    brand: '잔스포츠',
    name: '슈퍼브레이크 백팩',
    shortName: '백팩',
    originalPrice: 79000,
    price: 59000,
    imageAsset: 'assets/images/shop/backpack.png',
    colors: [Color(0xFF111111)],
    tabs: {'ranking', 'new'},
  ),
  ShopProduct(
    id: 'p11',
    rank: 11,
    rankChange: -3,
    brand: '유니클로',
    name: '오버핏 반팔 티셔츠',
    shortName: '반팔 티셔츠',
    originalPrice: 19900,
    price: 15900,
    imageAsset: 'assets/images/shop/tee.png',
    colors: [Color(0xFFFFFFFF), Color(0xFF111111)],
    tabs: {'ranking', 'sale'},
  ),
  ShopProduct(
    id: 'p12',
    rank: 12,
    rankChange: -6,
    brand: '아디다스',
    name: '아딜렛 슬라이드',
    shortName: '슬라이드',
    originalPrice: 39000,
    price: 29000,
    imageAsset: 'assets/images/shop/slides.png',
    colors: [Color(0xFF111111), Color(0xFFC9A227), Color(0xFFD9D9D9)],
    tabs: {'ranking', 'special'},
  ),
];

const demoNotifications = <DemoNotification>[
  DemoNotification(
    id: 'daily-report',
    title: '일일 리포트',
    timeLabel: '오늘 08:00',
    body: '오늘은 어제보다 3,200원 더 썼어요. 하지만 저번주와 흐름은 비슷해요',
  ),
  DemoNotification(
    id: 'weekly-report',
    title: '주간 리포트',
    timeLabel: '월요일 09:00',
    body: '이번주는 소비량이 13% 줄었지만, 더 자주 소비하고 있어요.',
  ),
  DemoNotification(
    id: 'daily-limit',
    title: '일일 소비량 알림',
    timeLabel: '오늘 21:14',
    body: '오늘 소비하기로 정한 한도를 넘었어요.',
  ),
];
